### ISSUE TITLE
Can start script

### ISSUE THREAD

**Issue by Nekspsy** [karthik947/NewCoinListingsBot#1]
Hi, i get error with script start, do you know how i can fix it?

```

C:\Users\admin\Desktop\NewCoinListingsBot-master\detect.js:15
      (await got(`https://api.binance.com/api/v3/exchangeInfo`))?.body
                                                                 ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Neks\Desktop\NewCoinListingsBot-master\index.js:3:30)
```

**Comment by karthik947** [comment]
Please check the nodejs version. I'm running on 14.2 an I don't get this error.

**Comment by Nekspsy** [comment]
updated but didn't help. ok thanks, I'll try to figure it out...

```
PS C:\Users\admin\Desktop\NewCoinListingsBot-master> npm -v
6.14.15

PS C:\Users\admin\Desktop\NewCoinListingsBot-master> node index.js
C:\Users\admin\Desktop\NewCoinListingsBot-master\detect.js:15
      (await got(`https://api.binance.com/api/v3/exchangeInfo`))?.body
                                                                 ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Neks\Desktop\NewCoinListingsBot-master\index.js:3:30)
```

**Comment by karthik947** [comment]
You are running on 6.14 version. Please upgrade and retry.
